apiVersion: v1
kind: Service
metadata:
  namespace: svc-ns
  name: dual-stack-web-svc
  labels:
    app: web-app
spec:
  ipFamilyPolicy: RequireDualStack
  ipFamilies: # the order here sets defienes which IP is primary. Only primary will be shown by `kubectl get``
    - IPv4
    - IPv6
  type: NodePort
  ports:
    - name: http
      nodePort: 30003
      targetPort: 80
      port: 80
      protocol: TCP
  selector:
    app: web-app
