kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: learning-cluster
networking:
  ipFamily: dual        
nodes:
- role: control-plane
  image: kindest/node:v1.27.2 # the kubectl version should not be more than one minor version higher or lower than the cluster.
- role: worker
  image: kindest/node:v1.27.2
- role: worker
  image: kindest/node:v1.27.2
- role: worker
  image: kindest/node:v1.27.2
