apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awesome-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
---
apiVersion: v1
kind: Pod
metadata:
  name: lucky-pod
spec:
  volumes:
    - name: local-db
      persistentVolumeClaim:
        claimName: awesome-pvc
  containers:
    - name: awesome-app
      image: ubuntu-ctr
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /data
          name: local-db
