apiVersion: v1
kind: Service
metadata:
  namespace: dps-ns
  name: web-svc
  labels:
    app: web-app
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30003
      targetPort: 80
      port: 80
      protocol: TCP
  selector:
    app: web-app
