apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-namespaces
rules:
  - apiGroups:
      - ""
    resources: ["namespaces"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespaces-manager
subjects:
  - kind: User
    name: k8s-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: manage-namespaces
  apiGroup: rbac.authorization.k8s.io
