apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-secrets
rules:
  - apiGroups:
      - ""
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-manager
  namespace: namespace-1
subjects:
  - kind: User
    name: k8s-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: manage-secrets
  apiGroup: rbac.authorization.k8s.io
