apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: namespace-1
  name: read-pods
rules:
  - apiGroups:
      - ""
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: namespace-2
  name: read-dps
rules:
  - apiGroups:
      - "apps"
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: namespace-3
  name: manage-configmaps
rules:
  - apiGroups:
      - ""
    resources: ["configmaps"]
    verbs: ["*"]
