apiVersion: v1
kind: Service
metadata:
  name: milky-way-svc
spec:
  type: ClusterIP
  selector:
    env: milky
    topic: universe
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: needle-galaxy-svc
spec:
  selector:
    env: needle
    topic: universe
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fireworks-galaxy-svc
spec:
  selector:
    env: fireworks
    topic: universe
  ports:
    - port: 80
      targetPort: 80


---
apiVersion: v1
kind: Pod
metadata:
  name: milky-way
  labels:
    env: milky
    topic: universe
spec:
  containers:
    - name: milky-way-app
      image: mikecode021/milky-way:1.0.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: needle-galaxy
  labels:
    env: needle
    topic: universe
spec:
  containers:
    - name: needle-galaxy-app
      image: mikecode021/needle-galaxy:1.0.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: fireworks-galaxy
  labels:
    env: fireworks
    topic: universe
spec:
  containers:
    - name: fireworks-galaxy-app
      image: mikecode021/fireworks-galaxy:1.0.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
