apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: universe-path-based
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx
  rules:
    - host: universe.com
      http:
        paths:
          - pathType: Prefix
            path: /milky-way
            backend:
              service:
                name: milky-way-svc
                port:
                  number: 80
          - pathType: Prefix
            path: /needle-galaxy
            backend:
              service:
                name: needle-galaxy-svc
                port:
                  number: 80
          - pathType: Prefix
            path: /fireworks-galaxy
            backend:
              service:
                name: fireworks-galaxy-svc
                port:
                  number: 80
