apiVersion: v1
kind: Pod
metadata:
  name: multimap-user
  labels:
    name: configmap
spec:
  containers:
    - name: multimap-user
      image: busybox
      command: ["sleep"]
      args: ["infinity"]
      env:
        - name: firstname
          valueFrom:
            configMapKeyRef:
              name: cm-entries
              key: name
        - name: lastname
          valueFrom:
            configMapKeyRef:
              name: cm-entries
              key: famName
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
