apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    label: secret
spec:
  volumes:
    - name: my-secret-vol
      secret:
        secretName: creds
  containers:
    - name: secret-pod
      image: nginx
      volumeMounts:
        - mountPath: "/etc/securedCreds"
          name: my-secret-vol
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
