apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: galaxies.michaelkora.com
spec:
  group: michaelkora.com
  scope: Cluster
  names:
    plural: galaxies
    singular: galaxy
    kind: Galaxy
    shortNames:
      - gx
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                galaxyName:
                  type: string
                galaxyShape:
                  type: string
                distance:
                  type: integer
      # The kubectl tool relies on server-side output formatting.
      # Your cluster's API server decides which columns are shown
      # by the kubectl get command. You can customize these columns
      # for a CustomResourceDefinition. The following example adds
      # the Spec, Replicas, and Age columns.
      additionalPrinterColumns:
        - name: Name
          type: string
          description: Name of the Galaxy
          jsonPath: .spec.galaxyName
        - name: Shape
          type: string
          description: Shape of the Galaxy
          jsonPath: .spec.galaxyShape
        - name: Distance
          type: integer
          description: Distance(in light year ) to Milky way
          jsonPath: .spec.distance
