apiVersion: v1
kind: Pod
metadata:
  name: multi-ctr-init-xpl
  labels:
    app: initializer
spec:
  volumes:
    - name: shared-data
      emptyDir: {}

  containers:
    - name: my-web-server
      image: nginx
      ports:
      - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "125m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      volumeMounts:
        - name: shared-data
          mountPath: "/usr/share/nginx/html"

  # initContainers:
  #   - name: init-ctr
  #     image: mikecode021/init-container:1.0.0
  #     command: ["/bin/sh"]    
  #     args:
  #       - python3
  #       - /app/downloader.py
  #     volumeMounts:
  #       - mountPath: "/tmp/app"
  #         name: shared-data

  initContainers:
    - name: install
      image: busybox:1.28
      command:
      - wget
      - "-O"
      - "/work-dir/index.html"
      - http://info.cern.ch
      volumeMounts:
      - name: shared-data 
        mountPath: "/work-dir"